export const MACRO_ANALYTICS_SCHEMA_VERSION_V1 = 1 as const;
export const MACRO_ANALYTICS_SCHEMA_VERSION_V2 = 2 as const;
export const MACRO_ANALYTICS_SCHEMA_VERSION_V3 = 3 as const;
export const MACRO_ANALYTICS_SCHEMA_VERSION_V4 = 4 as const;
export const MACRO_ANALYTICS_SCHEMA_VERSION_V5 = 5 as const;
export const MACRO_ANALYTICS_SCHEMA_VERSION = MACRO_ANALYTICS_SCHEMA_VERSION_V5;
export type MacroAnalyticsSchemaVersion = typeof MACRO_ANALYTICS_SCHEMA_VERSION_V1 | typeof MACRO_ANALYTICS_SCHEMA_VERSION_V2 | typeof MACRO_ANALYTICS_SCHEMA_VERSION_V3 | typeof MACRO_ANALYTICS_SCHEMA_VERSION_V4 | typeof MACRO_ANALYTICS_SCHEMA_VERSION_V5;
