import { TransactionComposerView } from './TransactionComposerView';
import type { TransactionEntryViewProps } from './TransactionEntryView.contract';

export type {
  TransactionEntryViewProps,
  TransactionEntryViewProvided,
  TransactionEntryViewRequired,
} from './TransactionEntryView.contract';

export function TransactionEntryView({ required, provided }: TransactionEntryViewProps) {
  return (
    <TransactionComposerView
      required={{
        open: required.state.open,
        mode: required.state.mode,
        disabled: required.status.disabled,
        amount: required.state.amount,
        date: required.state.date,
        nextScheduledOccurrenceDate: required.state.nextScheduledOccurrenceDate,
        note: required.state.note,
        categoryInput: required.state.categoryInput,
        categoryOptions: required.state.categoryOptions,
        tagInput: required.state.tagInput,
        tagOptions: required.state.tagOptions,
        advancedOpen: required.state.advancedOpen,
        transferTargetAccountId: required.state.transferTargetAccountId,
        transferTargetOptions: required.state.transferTargetOptions,
        transferAmountIn: required.state.transferAmountIn,
        transferFxRate: required.state.transferFxRate,
        transferFxMode: required.state.transferFxMode,
        transferDestinationCurrency: required.state.transferDestinationCurrency,
        transferCrossCurrency: required.state.transferCrossCurrency,
        expenseDetailed: required.state.splitEnabled,
        splitEditorOpen: required.state.splitEditorOpen,
        splitApplied: required.state.splitApplied,
        expenseItems: required.state.splitItems,
        expenseItemName: required.state.splitItemName,
        expenseItemAmount: required.state.splitItemAmount,
        editingExpenseItemId: required.state.editingSplitItemId,
        expenseRemaining: required.state.splitRemaining,
        expenseSplitTotal: required.state.splitTotal,
        schedulingMode: required.state.schedulingMode,
        schedulingKind: required.state.schedulingKind,
        recurrenceFrequency: required.state.recurrenceFrequency,
        recurrenceInterval: required.state.recurrenceInterval,
        recurrenceWeeklyDay: required.state.recurrenceWeeklyDay,
        recurrenceMonthlyPattern: required.state.recurrenceMonthlyPattern,
        recurrenceDayOfMonth: required.state.recurrenceDayOfMonth,
        recurrenceMonthlyOrdinal: required.state.recurrenceMonthlyOrdinal,
        recurrenceMonthlyWeekday: required.state.recurrenceMonthlyWeekday,
        recurrenceEndKind: required.state.recurrenceEndKind,
        recurrenceEndDate: required.state.recurrenceEndDate,
        recurrenceEndCount: required.state.recurrenceEndCount,
        scheduleEditorOpen: required.state.scheduleEditorOpen,
        expected: required.state.expected,
        editedScheduledMovementId: required.state.editedScheduledMovementId,
        postExpectedMovementId: required.state.postExpectedMovementId,
        currencyCode: required.state.currencyCode,
        expenseItemNameError: required.status.errors.expenseItemName,
        expenseItemAmountError: required.status.errors.expenseItemAmount,
        expenseSplitError: required.status.errors.expenseSplit,
        amountError: required.status.errors.amount,
        transferAmountInError: required.status.errors.transferAmountIn,
        transferFxRateError: required.status.errors.transferFxRate,
        dateError: required.status.errors.date,
        recurrenceIntervalError: required.status.errors.recurrenceInterval,
        recurrenceEndDateError: required.status.errors.recurrenceEndDate,
        recurrenceEndCountError: required.status.errors.recurrenceEndCount,
        expectedConflictError: required.status.errors.expectedConflict,
      }}
      provided={{
        onOpen: provided.commands.open,
        onClose: provided.commands.close,
        onSelectMode: provided.commands.selectMode,
        onToggleAdvanced: provided.commands.toggleAdvanced,
        onSetAmount: provided.commands.setAmount,
        onSetDate: provided.commands.setDate,
        onSetNote: provided.commands.setNote,
        onSetCategoryInput: provided.commands.setCategoryInput,
        onSetTagInput: provided.commands.setTagInput,
        onSetTransferTarget: provided.commands.setTransferTarget,
        onSetTransferAmountIn: provided.commands.setTransferAmountIn,
        onSetTransferFxRate: provided.commands.setTransferFxRate,
        onSetTransferFxMode: provided.commands.setTransferFxMode,
        onToggleExpenseDetailed: () => provided.commands.setSplitEnabled(!required.state.splitEnabled),
        onOpenSplitEditor: provided.commands.openSplitEditor,
        onCloseSplitEditor: provided.commands.closeSplitEditor,
        onApplySplit: provided.commands.applySplit,
        onRemoveSplit: provided.commands.removeSplit,
        onSetExpenseItemName: provided.commands.setSplitItemName,
        onSetExpenseItemAmount: provided.commands.setSplitItemAmount,
        onStartExpenseItem: provided.commands.startSplitItem,
        onCancelExpenseItem: provided.commands.cancelSplitItem,
        onAddExpenseItem: provided.commands.addSplitItem,
        onEditExpenseItem: provided.commands.editSplitItem,
        onRemoveExpenseItem: provided.commands.removeSplitItem,
        onAssignRemaining: provided.commands.assignSplitRemaining,
        onSplitByParts: provided.commands.splitByParts,
        onSetSchedulingMode: provided.commands.setSchedulingMode,
        onSetSchedulingKind: provided.commands.setSchedulingKind,
        onOpenRecurringScheduleEditor: provided.commands.openRecurringScheduleEditor,
        onApplyRecurringSchedule: provided.commands.applyRecurringSchedule,
        onCloseRecurringScheduleEditor: provided.commands.closeRecurringScheduleEditor,
        onRemoveRecurringSchedule: provided.commands.removeRecurringSchedule,
        onSetRecurrenceFrequency: provided.commands.setRecurrenceFrequency,
        onSetRecurrenceInterval: provided.commands.setRecurrenceInterval,
        onSetRecurrenceWeeklyDay: provided.commands.setRecurrenceWeeklyDay,
        onSetRecurrenceMonthlyPattern: provided.commands.setRecurrenceMonthlyPattern,
        onSetRecurrenceDayOfMonth: provided.commands.setRecurrenceDayOfMonth,
        onSetRecurrenceMonthlyOrdinal: provided.commands.setRecurrenceMonthlyOrdinal,
        onSetRecurrenceMonthlyWeekday: provided.commands.setRecurrenceMonthlyWeekday,
        onSetRecurrenceEndKind: provided.commands.setRecurrenceEndKind,
        onSetRecurrenceEndDate: provided.commands.setRecurrenceEndDate,
        onSetRecurrenceEndCount: provided.commands.setRecurrenceEndCount,
        onSetExpected: provided.commands.setExpected,
        onSubmit: provided.commands.submit,
      }}
    />
  );
}
